# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run prepare

# Expose port if needed (not sure, MCP communicates via stdio probably)

# Run the MCP server from the installed binary
CMD ["node", "lib/index.mjs"]
